//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int id { get; set; }
        public string FeatureName { get; set; }
        public Nullable<bool> completed { get; set; }
        public string notes { get; set; }
    }
}
