//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> isApproved { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
