//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLoan
    {
        public int Sloan_Id { get; set; }
        public string PlanType { get; set; }
        public Nullable<int> AnnualThreshold { get; set; }
        public Nullable<decimal> PercentDeduction { get; set; }
    }
}
